name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Bun
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies (if needed for post-deployment tasks)
      - name: Install dependencies
        run: bun install